services:
  - type: web
    name: genopilot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: DISABLE_PDF
        value: "1"
